### ISSUE TITLE
"More Episodes" mixes up seasons/episodes for shows

### ISSUE THREAD

**Issue by drinfernoo** [cartmandos/skin.titan.bingie.mode#4]
I've tested this by adding a few shows to my library, in order to get something to show up when I choose "More Episodes" in the Netflix Info dialog.

When I choose "More Episodes", I get a mixed up list of all seasons of all shows in my library. Even worse, choosing one of the seasons shows all episodes from all shows that have that season. If I pick "Season 1" of any show, I get all the episodes from all of those shows' first seasons.

For example: https://imgur.com/a/HbX7dQM

**Comment by drinfernoo** [comment]
This only appears to happen with content added as .strm files, and not with local content.

**Comment by cartmandos** [comment]
do you add manually/via addon? I'd like to test it sometime.

**Comment by drinfernoo** [comment]
@cartmandos Yeah, just from the "Add to Library" context menu option in most add-ons. I believe I tested it with Yoda.

**Comment by cartmandos** [comment]
Just bumped updates to repo, please test and let me know if that solves the issue.
