### ISSUE TITLE
Subtitles Settings Button 

### ISSUE THREAD

**Issue by jsnj** [cartmandos/skin.titan.bingie.mode#7]
Video OSD subtitles button needs to point to the new subtitle settings OSD.

**Comment by cartmandos** [comment]
It doesn't NEED to activate the new osdsubtitlesettings. It's a question of preference at the moment. Whether to have it as it currently is or with a built-in dialog. For now, I'm more inclined with keeping it as it was. All the options are the same and are working.

**Comment by jsnj** [comment]
_"All the options are the same and are working."_

For users who have downloaded subtitles to a specific folder on their drive, "browse for subtitle" is missing. Also, for movies & shows that come with multiple subtitles in various languages, it's more convenient and expedient to scroll through a visible list than to navigate blindly using the "next" button.

**Comment by cartmandos** [comment]
Point taken. will look into it.

**Comment by cartmandos** [comment]
@jsnj I've added the option for native subtitles dialog, will be available to switch current/native dialog in skinsettings. Hopefully will release soon.

**Comment by tkleinhenz** [comment]
JSON PLEASE CALL ME ASAP  GHST I NEED TO TALK WITH YOU PLEASE>  LOVE TROY

**Comment by tkleinhenz** [comment]
PLEAES HAVE JASON JEFFERy CALL ME ASAP  I NEED TO TALK WITH you ASAP

**Comment by tkleinhenz** [comment]
JASON PLESE CALL ME

**Comment by tkleinhenz** [comment]
JASON PLESAE CALL ME ASAP

**Comment by tkleinhenz** [comment]
JASON PLEASE CALL ME SAP
